### ISSUE TITLE
QGIS Server 3

### ISSUE THREAD

**Issue by alexgleith** [kartoza/docker-qgis-server#15]
Is is likely this process will work for QGIS Server 3?

I can set up a PR, if you like. Just wanted to confirm that it will work before I get stuck in...

**Comment by timlinux** [comment]
So yes the idea is to get the desktop image working (I received a patch for that but it does not yet build cleanly) then make a 3.0 image.

See https://github.com/kartoza/docker-qgis-desktop/pull/33

**Comment by timlinux** [comment]
Just an update - I have a desktop image made now for 3.0.3 and will soon have the 3.0 server image out.

**Comment by timlinux** [comment]
Ok first QGIS 3 images are available:

![screen shot 2018-05-30 at 08 51 27](https://user-images.githubusercontent.com/178003/40703830-c1872332-63e6-11e8-99d9-4af1fc0bc3ab.png)

docker pull kartoza/qgis-server:3.0

or for a specific release

docker pull kartoza/qgis-server:3.0.3

Please test and file issues at https://github.com/kartoza/docker-qgis-server/issues if you encounter them.

The image is rather large 929mb as opposed to the 2.x image which is 460mb. This is because I have not stripped out the dev packages and aggressively cleaned up stuff from the QGIS base image. That will be my next todo.

**Comment by alexgleith** [comment]
Thanks Tim, this is awesome!

I am not likely to have a chance to test soon, but will stick it on my list of todos and get to it eventually. ;-)
